#!/usr/bin/env bash
function usage() {
cat <<EOF
osxvpncli 0.1
https://github.com/jonhiggs/osxvpncli

Description:
  Establish or terminate VPN connections from an OSX command line

Usage:
  $(basename $0) [OPTION] [vpn_name]

Options:
  connect     <vpn_name>  Establish a new connection
  disconnect  [vpn_name]  Terminate established connections
  status      [vpn_name]  Show connection status
EOF
exit 1
}

function connections() {
  scutil --nc list | awk '
    BEGIN         { FS="\"" }
    /^\*/ {
      if ( /PPP:L2TP.$/ ) { print $2 }
      if ( /IPSec.$/ )    { print $2 }
      if ( /PPP:PPTP.$/ ) { print $2 }
    }
  ' | sort
}

function connection_status() {
  IFS=$'\n'
  for c in $(connections); do
    echo -e "$c\t$(scutil --nc status "$c" | head -n1)"
  done
}

f=$1
shift
c=$(echo $@ | sed 's#\ #\\\ #g')

case $f in
  "connect")
    [[ -z $c ]] && echo "VPN not provided" 1>&2 && exit 1
    eval "scutil --nc start '$c'"
  ;;

  "disconnect")
    [[ -z $c ]] && echo "VPN not provided" 1>&2 && exit 1
    osascript -e "tell application \"System Events\""                \
              -e "  tell current location of network preferences"    \
              -e "    set VPN to service \"$(echo $c | tr -d '\')\"" \
              -e "    if exists VPN then disconnect VPN"             \
              -e "  end tell"                                        \
              -e "end tell"                                          >/dev/null
  ;;

  "status")
    connection_status | column -ts $'\t'
  ;;
  *)        usage                                 ;;
esac
