#!/usr/bin/env bash
function usage() {
cat <<EOF
osxvpncli 0.2.1
https://github.com/jonhiggs/osxvpncli

Description:
  Establish or terminate VPN connections from an OSX command line

Usage:
  $(basename $0) [OPTION] [vpn_name]

Options:
  connect     <vpn_name>  Establish a new connection
  disconnect  [vpn_name]  Terminate established connections
  status      [vpn_name]  Show connection status
EOF
exit 1
}

function connections() {
  scutil --nc list | awk '
    BEGIN { FS="\"" }
    /^\*/ {
      if ( /PPP:L2TP.$/ ) { print $2 }
      if ( /IPSec.$/ )    { print $2 }
      if ( /PPP:PPTP.$/ ) { print $2 }
    }
  ' | sort
}

function connection_status() {
  IFS=$'\n'
  for c in ${1:-$(connections)}; do
    echo -e "$c\t$(scutil --nc status "$c" | head -n1)"
  done
}

f=$1
shift

case $f in
  "connect")
    [[ $# -eq 0 ]] && echo "VPN not provided" 1>&2 && exit 1
    scutil --nc start "$@"
  ;;

  "disconnect")
    if [[ $# -eq 0 ]]; then
      connections=$(connection_status | awk -F$'\t' '/Connected$/ { print $1 }')
    else
      connections="$@"
    fi

    IFS=$'\n'
    for connection in ${connections}; do
      scutil --nc stop "${connection}"
    done
  ;;

  "status") connection_status "$@" | column -ts $'\t'  ;;
  *)        usage                                      ;;
esac
